# Exploring NumPy Library

In [7]:
import numpy as np

In [3]:
import numpy as np
my_list = [1, 2, 3]
np.array(my_list)

array([1, 2, 3])

In [4]:
l1 =  [1, 2, 3]
l2 =  [5, 6, 7]
arr1 = np.array(l1)
arr2 = np.array(l2)


In [5]:
# addition of induvidual elements  are possible in numpy 
arr1+arr2

array([ 6,  8, 10])

### Type

In [6]:
arr1.dtype

dtype('int32')

In [7]:
arr3= np.array ([1,3,4,5,'a'])

In [8]:
arr3


array(['1', '3', '4', '5', 'a'], dtype='<U11')

### Arrays are homogenous

In [12]:
arr4 = np.array(([1,2,3], [4,5,6], [7,8,9]))

In [13]:
arr4


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Size

In [14]:
arr4.size

9

### Shape

In [15]:
arr4.shape


(3, 3)

### Creating a 2D array

In [16]:
arr5= np.array(([1,2], [3,4]))
arr5

array([[1, 2],
       [3, 4]])

In [18]:
arr5.shape


(2, 2)

In [19]:
arr5.ndim

2

In [20]:
arr5.size

4

In [43]:
arr6 = np.array(list(range(5,10)))
arr6
                

array([5, 6, 7, 8, 9])

In [29]:
arr7 = np.arange(10,100,3)
arr7

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [38]:
arr8 = np.arange(1,101)
arr8

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [39]:
arr8.reshape(25,4)

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16],
       [ 17,  18,  19,  20],
       [ 21,  22,  23,  24],
       [ 25,  26,  27,  28],
       [ 29,  30,  31,  32],
       [ 33,  34,  35,  36],
       [ 37,  38,  39,  40],
       [ 41,  42,  43,  44],
       [ 45,  46,  47,  48],
       [ 49,  50,  51,  52],
       [ 53,  54,  55,  56],
       [ 57,  58,  59,  60],
       [ 61,  62,  63,  64],
       [ 65,  66,  67,  68],
       [ 69,  70,  71,  72],
       [ 73,  74,  75,  76],
       [ 77,  78,  79,  80],
       [ 81,  82,  83,  84],
       [ 85,  86,  87,  88],
       [ 89,  90,  91,  92],
       [ 93,  94,  95,  96],
       [ 97,  98,  99, 100]])

In [40]:
arr8.reshape(4,25)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
         89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [41]:
arr8.reshape(50,2)

array([[  1,   2],
       [  3,   4],
       [  5,   6],
       [  7,   8],
       [  9,  10],
       [ 11,  12],
       [ 13,  14],
       [ 15,  16],
       [ 17,  18],
       [ 19,  20],
       [ 21,  22],
       [ 23,  24],
       [ 25,  26],
       [ 27,  28],
       [ 29,  30],
       [ 31,  32],
       [ 33,  34],
       [ 35,  36],
       [ 37,  38],
       [ 39,  40],
       [ 41,  42],
       [ 43,  44],
       [ 45,  46],
       [ 47,  48],
       [ 49,  50],
       [ 51,  52],
       [ 53,  54],
       [ 55,  56],
       [ 57,  58],
       [ 59,  60],
       [ 61,  62],
       [ 63,  64],
       [ 65,  66],
       [ 67,  68],
       [ 69,  70],
       [ 71,  72],
       [ 73,  74],
       [ 75,  76],
       [ 77,  78],
       [ 79,  80],
       [ 81,  82],
       [ 83,  84],
       [ 85,  86],
       [ 87,  88],
       [ 89,  90],
       [ 91,  92],
       [ 93,  94],
       [ 95,  96],
       [ 97,  98],
       [ 99, 100]])

In [42]:
arr8.reshape(2,50)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
         77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
         90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [47]:
L = range (1000)
%timeit nums = (i**2 for i in L)


786 ns ± 126 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [45]:
nums = np.arange(1000)
%timeit nums**2

3.54 µs ± 574 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [44]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [48]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [49]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
np.diag(([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [64]:
z = np.diag(([1,2,3,4]))
np.diag(z)

array([1, 2, 3, 4])

### Calculating STD.DEV in Numpy

In [51]:
x= np.array(range(1,100))

In [52]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [62]:
sum = np.sum (x)
sum

4950

In [57]:

mean = np.mean(x)
mean


50.0

In [61]:
std_dev =  np.sqrt(np.sum((x - np.mean(x))**2)/np.size(x))
std_dev

28.577380332470412

In [63]:
np.std(x)

28.577380332470412

### Random Number generation

In [66]:
# For uniform distribution
d = np.random.random(3)
d

array([0.91203864, 0.26480362, 0.90341441])

In [67]:
# For Normal distribution
a = np.random.randn(5)
a

array([-0.93196623, -0.27929942, -0.87593921,  1.48284052, -0.59343667])

In [68]:
# for sampling integers
np.random.randint(0,20,3) # means sampling 3 numbers between 0 to 20

array([18, 17,  2])

In [69]:
np.random.randint(0,20,3)

array([ 8,  6, 10])

In [8]:
a = np.arange(10, dtype=np.float64)
a


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [74]:
np.array([True, False, True]).dtype

dtype('bool')

In [75]:
b = np.arange(10)
b


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
a[3]= 9

In [9]:
a


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [79]:
b= a[ : : 2]

In [80]:
b

array([0., 2., 4., 6., 8.])

In [81]:
b= a[10 : : -2]
b

array([9., 7., 5., 9., 1.])

In [86]:
b = a[: : -2]
b

array([9., 7., 5., 9., 1.])

In [87]:
b = a[1: :2][: :-1]
b

array([9., 7., 5., 9., 1.])

In [88]:
np.shares_memory(a,b)

True

In [10]:
c = a[ : :2].copy()

In [90]:
np.shares_memory(a,c)

False

In [94]:
a = np.zeros((4,4))
b = np.ones((4,4))
print (a)
print (b)



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [97]:
c = np.vstack ((a,b))
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [98]:
c.shape

(8, 4)

In [99]:
d = np.hstack((a,b))
d

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [100]:
d.shape

(4, 8)

In [101]:
np.concatenate([a,b], axis = 1)

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [102]:
np.concatenate([a,b], axis = 0)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [111]:
array1 = np.array([1,2,3])
array1

array([1, 2, 3])

In [113]:
array1.shape

(3,)

In [112]:
array1.T.shape



(3,)

In [108]:
a = np.arange(4)
b = a.T
np.dot(a,b)

14