# NumPy

In [132]:
import pandas as pd
import numpy as np
df = pd.read_csv("C:\\Users\\kiran\\Downloads\\auto-mpg.csv")
df

mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130    3504          12.0   
1    15.0          8         350.0        165    3693          11.5   
2    18.0          8         318.0        150    3436          11.0   
3    16.0          8         304.0        150    3433          12.0   
4    17.0          8         302.0        140    3449          10.5   
..    ...        ...           ...        ...     ...           ...   
393  27.0          4         140.0         86    2790          15.6   
394  44.0          4          97.0         52    2130          24.6   
395  32.0          4         135.0         84    2295          11.6   
396  28.0          4         120.0         79    2625          18.6   
397  31.0          4         119.0         82    2720          19.4   

     model year  origin                   car name  
0            70       1  chevrolet chevelle malibu  
1            70       1          buick skylark 320  
2            70       1         plymouth satellite  
3            70       1              amc rebel sst  
4            70       1                ford torino  
..          ...     ...                        ...  
393          82       1            ford mustang gl  
394          82       2                  vw pickup  
395          82       1              dodge rampage  
396          82       1                ford ranger  
397          82       1                 chevy s-10  

[398 rows x 9 columns]

### 1. Basic Array Operations
 - Convert the mpg column into a NumPy array and calculate:
 - The mean, median, and standard deviation of mpg.
 - The number of cars with mpg greater than 25.

In [133]:
# Converting mpg column into a NumPy array
import pandas as pd
import numpy as np
df = pd.read_csv("C:\\Users\\kiran\\Downloads\\auto-mpg.csv")
mpg = np.array(df["mpg"])
mpg

array([18. , 15. , 18. , 16. , 17. , 15. , 14. , 14. , 14. , 15. , 15. ,
       14. , 15. , 14. , 24. , 22. , 18. , 21. , 27. , 26. , 25. , 24. ,
       25. , 26. , 21. , 10. , 10. , 11. ,  9. , 27. , 28. , 25. , 25. ,
       19. , 16. , 17. , 19. , 18. , 14. , 14. , 14. , 14. , 12. , 13. ,
       13. , 18. , 22. , 19. , 18. , 23. , 28. , 30. , 30. , 31. , 35. ,
       27. , 26. , 24. , 25. , 23. , 20. , 21. , 13. , 14. , 15. , 14. ,
       17. , 11. , 13. , 12. , 13. , 19. , 15. , 13. , 13. , 14. , 18. ,
       22. , 21. , 26. , 22. , 28. , 23. , 28. , 27. , 13. , 14. , 13. ,
       14. , 15. , 12. , 13. , 13. , 14. , 13. , 12. , 13. , 18. , 16. ,
       18. , 18. , 23. , 26. , 11. , 12. , 13. , 12. , 18. , 20. , 21. ,
       22. , 18. , 19. , 21. , 26. , 15. , 16. , 29. , 24. , 20. , 19. ,
       15. , 24. , 20. , 11. , 20. , 21. , 19. , 15. , 31. , 26. , 32. ,
       25. , 16. , 16. , 18. , 16. , 13. , 14. , 14. , 14. , 29. , 26. ,
       26. , 31. , 32. , 28. , 24. , 26. , 24. , 26

In [134]:
# Calculating mean of mpg
mean = np.mean(mpg)
mean


23.514572864321607

In [135]:
# Calculating Median of mpg
median = np.median(mpg)
median

23.0

In [136]:
# Calculating Standard deviation of mpg
std_dev = np.std(mpg)
std_dev

7.806159061274433

In [137]:
# The number of cars with mpg greater than 25.
mpg = np.array(df["mpg"])
cars_mpg_above25_count = np.count_nonzero(mpg>25)
cars_mpg_above25_count

158

### 2. Filtering
- Using NumPy, filter all cars with more than 6 cylinders.
- Return the corresponding car_name as a list.


In [138]:
# Using NumPy, filter all cars with more than 6 cylinders.
cyli_6 = np.array(df.cylinders > 6)
cars_cylin6 = df[cyli_6]
cars_cylin6

mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130    3504          12.0   
1    15.0          8         350.0        165    3693          11.5   
2    18.0          8         318.0        150    3436          11.0   
3    16.0          8         304.0        150    3433          12.0   
4    17.0          8         302.0        140    3449          10.5   
..    ...        ...           ...        ...     ...           ...   
291  19.2          8         267.0        125    3605          15.0   
292  18.5          8         360.0        150    3940          13.0   
298  23.0          8         350.0        125    3900          17.4   
300  23.9          8         260.0         90    3420          22.2   
364  26.6          8         350.0        105    3725          19.0   

     model year  origin                              car name  
0            70       1             chevrolet chevelle malibu  
1            70       1                     buick skylark 320  
2            70       1                    plymouth satellite  
3            70       1                         amc rebel sst  
4            70       1                           ford torino  
..          ...     ...                                   ...  
291          79       1         chevrolet malibu classic (sw)  
292          79       1  chrysler lebaron town @ country (sw)  
298          79       1                     cadillac eldorado  
300          79       1     oldsmobile cutlass salon brougham  
364          81       1                 oldsmobile cutlass ls  

[103 rows x 9 columns]

In [139]:
# Return the corresponding car_name as a list.
np.array(cars_cylin6["car name"]).tolist()


['chevrolet chevelle malibu',
 'buick skylark 320',
 'plymouth satellite',
 'amc rebel sst',
 'ford torino',
 'ford galaxie 500',
 'chevrolet impala',
 'plymouth fury iii',
 'pontiac catalina',
 'amc ambassador dpl',
 'dodge challenger se',
 "plymouth 'cuda 340",
 'chevrolet monte carlo',
 'buick estate wagon (sw)',
 'ford f250',
 'chevy c20',
 'dodge d200',
 'hi 1200d',
 'chevrolet impala',
 'pontiac catalina brougham',
 'ford galaxie 500',
 'plymouth fury iii',
 'dodge monaco (sw)',
 'ford country squire (sw)',
 'pontiac safari (sw)',
 'chevrolet impala',
 'pontiac catalina',
 'plymouth fury iii',
 'ford galaxie 500',
 'amc ambassador sst',
 'mercury marquis',
 'buick lesabre custom',
 'oldsmobile delta 88 royale',
 'chrysler newport royal',
 'amc matador (sw)',
 'chevrolet chevelle concours (sw)',
 'ford gran torino (sw)',
 'plymouth satellite custom (sw)',
 'buick century 350',
 'amc matador',
 'chevrolet malibu',
 'ford gran torino',
 'dodge coronet custom',
 'mercury marquis brou

### 3. Statistical Analysis
- Compute the 25th, 50th, and 75th percentiles of the weight column using NumPy

In [140]:
# 25th percentile
Weight = np.array(df["weight"]).tolist()
Total_values = len(Weight)
weight_asc = sorted(Weight)
percentile_25th = weight_asc[(25*Total_values)//100]
percentile_25th 

2223

In [141]:
percent_25 = np.percentile(Weight,25) 
percent_25

2223.75

In [142]:
# 50th percentile
Weight = np.array(df["weight"]).tolist()
Total_values = len(Weight)
weight_asc = sorted(Weight)
percentile_50th = weight_asc[(50*Total_values)//100]
percentile_50th 

2807

In [143]:
percent_50 = np.percentile(Weight,50) 
percent_50

2803.5

In [144]:
percent_50 = np.median(Weight) 
percent_50

2803.5

In [145]:
# 75th percentile
Weight = np.array(df["weight"]).tolist()
Total_values = len(Weight)
weight_asc = sorted(Weight)
percentile_75th = weight_asc[(75*Total_values)//100]
percentile_75th 

3609

In [146]:
percent_75 = np.percentile(Weight,75) 
percent_75

3608.0

### 4. Array Manipulation
- Convert the acceleration column into a NumPy array and normalize its values
(scale between 0 and 1).


In [147]:
Acceleration = np.array(df["acceleration"])
Acceleration

array([12. , 11.5, 11. , 12. , 10.5, 10. ,  9. ,  8.5, 10. ,  8.5, 10. ,
        8. ,  9.5, 10. , 15. , 15.5, 15.5, 16. , 14.5, 20.5, 17.5, 14.5,
       17.5, 12.5, 15. , 14. , 15. , 13.5, 18.5, 14.5, 15.5, 14. , 19. ,
       13. , 15.5, 15.5, 15.5, 15.5, 12. , 11.5, 13.5, 13. , 11.5, 12. ,
       12. , 13.5, 19. , 15. , 14.5, 14. , 14. , 19.5, 14.5, 19. , 18. ,
       19. , 20.5, 15.5, 17. , 23.5, 19.5, 16.5, 12. , 12. , 13.5, 13. ,
       11.5, 11. , 13.5, 13.5, 12.5, 13.5, 12.5, 14. , 16. , 14. , 14.5,
       18. , 19.5, 18. , 16. , 17. , 14.5, 15. , 16.5, 13. , 11.5, 13. ,
       14.5, 12.5, 11.5, 12. , 13. , 14.5, 11. , 11. , 11. , 16.5, 18. ,
       16. , 16.5, 16. , 21. , 14. , 12.5, 13. , 12.5, 15. , 19. , 19.5,
       16.5, 13.5, 18.5, 14. , 15.5, 13. ,  9.5, 19.5, 15.5, 14. , 15.5,
       11. , 14. , 13.5, 11. , 16.5, 17. , 16. , 17. , 19. , 16.5, 21. ,
       17. , 17. , 18. , 16.5, 14. , 14.5, 13.5, 16. , 15.5, 16.5, 15.5,
       14.5, 16.5, 19. , 14.5, 15.5, 14. , 15. , 15

In [148]:
max_value = np.max(Acceleration)
min_value = np.min(Acceleration)
Accel_normalize = (Acceleration-min_value)/(max_value-min_value)
Accel_normalize

array([0.23809524, 0.20833333, 0.17857143, 0.23809524, 0.14880952,
       0.11904762, 0.05952381, 0.0297619 , 0.11904762, 0.0297619 ,
       0.11904762, 0.        , 0.08928571, 0.11904762, 0.41666667,
       0.44642857, 0.44642857, 0.47619048, 0.38690476, 0.74404762,
       0.56547619, 0.38690476, 0.56547619, 0.26785714, 0.41666667,
       0.35714286, 0.41666667, 0.32738095, 0.625     , 0.38690476,
       0.44642857, 0.35714286, 0.6547619 , 0.29761905, 0.44642857,
       0.44642857, 0.44642857, 0.44642857, 0.23809524, 0.20833333,
       0.32738095, 0.29761905, 0.20833333, 0.23809524, 0.23809524,
       0.32738095, 0.6547619 , 0.41666667, 0.38690476, 0.35714286,
       0.35714286, 0.68452381, 0.38690476, 0.6547619 , 0.5952381 ,
       0.6547619 , 0.74404762, 0.44642857, 0.53571429, 0.92261905,
       0.68452381, 0.50595238, 0.23809524, 0.23809524, 0.32738095,
       0.29761905, 0.20833333, 0.17857143, 0.32738095, 0.32738095,
       0.26785714, 0.32738095, 0.26785714, 0.35714286, 0.47619

### 5. Broadcasting
- Increase all horsepower values by 10% and store the updated values in a new NumPy array. Handle missing data (if any) by replacing it with the mean of the column before applying the increase.


In [149]:
all_Horsepower = np.array(df["horsepower"]) # Getting the horsepower values as a numpy array
Horsepower = np.array(df[df["horsepower"]!= "?"]["horsepower"]) # horsepower values except those values with "?"string
Hrs_pwr = Horsepower.astype(float) # changing the data type to int fronm string
Mean = np.round(np.mean(Hrs_pwr),2) # Mean of all the values except the string "?"
all_Horsepower[all_Horsepower == "?"] = Mean
all_Horsepower.astype(float) # All horsepower values with "?" string replaced by mean value

array([130.  , 165.  , 150.  , 150.  , 140.  , 198.  , 220.  , 215.  ,
       225.  , 190.  , 170.  , 160.  , 150.  , 225.  ,  95.  ,  95.  ,
        97.  ,  85.  ,  88.  ,  46.  ,  87.  ,  90.  ,  95.  , 113.  ,
        90.  , 215.  , 200.  , 210.  , 193.  ,  88.  ,  90.  ,  95.  ,
       104.47, 100.  , 105.  , 100.  ,  88.  , 100.  , 165.  , 175.  ,
       153.  , 150.  , 180.  , 170.  , 175.  , 110.  ,  72.  , 100.  ,
        88.  ,  86.  ,  90.  ,  70.  ,  76.  ,  65.  ,  69.  ,  60.  ,
        70.  ,  95.  ,  80.  ,  54.  ,  90.  ,  86.  , 165.  , 175.  ,
       150.  , 153.  , 150.  , 208.  , 155.  , 160.  , 190.  ,  97.  ,
       150.  , 130.  , 140.  , 150.  , 112.  ,  76.  ,  87.  ,  69.  ,
        86.  ,  92.  ,  97.  ,  80.  ,  88.  , 175.  , 150.  , 145.  ,
       137.  , 150.  , 198.  , 150.  , 158.  , 150.  , 215.  , 225.  ,
       175.  , 105.  , 100.  , 100.  ,  88.  ,  95.  ,  46.  , 150.  ,
       167.  , 170.  , 180.  , 100.  ,  88.  ,  72.  ,  94.  ,  90.  ,
      

In [150]:
hrs_pwr_incr10 = all_Horsepower.astype(float) * 1.1  # increasing the horsepower by 10%
hrs_pwr_incr10



array([143.   , 181.5  , 165.   , 165.   , 154.   , 217.8  , 242.   ,
       236.5  , 247.5  , 209.   , 187.   , 176.   , 165.   , 247.5  ,
       104.5  , 104.5  , 106.7  ,  93.5  ,  96.8  ,  50.6  ,  95.7  ,
        99.   , 104.5  , 124.3  ,  99.   , 236.5  , 220.   , 231.   ,
       212.3  ,  96.8  ,  99.   , 104.5  , 114.917, 110.   , 115.5  ,
       110.   ,  96.8  , 110.   , 181.5  , 192.5  , 168.3  , 165.   ,
       198.   , 187.   , 192.5  , 121.   ,  79.2  , 110.   ,  96.8  ,
        94.6  ,  99.   ,  77.   ,  83.6  ,  71.5  ,  75.9  ,  66.   ,
        77.   , 104.5  ,  88.   ,  59.4  ,  99.   ,  94.6  , 181.5  ,
       192.5  , 165.   , 168.3  , 165.   , 228.8  , 170.5  , 176.   ,
       209.   , 106.7  , 165.   , 143.   , 154.   , 165.   , 123.2  ,
        83.6  ,  95.7  ,  75.9  ,  94.6  , 101.2  , 106.7  ,  88.   ,
        96.8  , 192.5  , 165.   , 159.5  , 150.7  , 165.   , 217.8  ,
       165.   , 173.8  , 165.   , 236.5  , 247.5  , 192.5  , 115.5  ,
       110.   , 110.

### 6. Boolean Indexing
- Find the average displacement of cars with an origin of 2 (Europe) using NumPy
indexing

In [151]:
displcmnt_orgin2 = np.array(df[df["origin"] == 2]["displacement"])
Avg_dsplcmnt_org2 = np.mean(displcmnt_orgin2)
np.round(Avg_dsplcmnt_org2,2)

109.14

### 7. Matrix Operations
- Create a 2D NumPy array containing the columns mpg, horsepower, and weight.
- Compute the dot product of this matrix with a given vector [1, 0.5, -0.2]

In [152]:
df["horsepower_new"] = all_Horsepower.astype(float)
array_2d = np.array(df[["mpg", "horsepower_new","weight"]]) 
v1 = np.array([1, 0.5, -0.2])
v1t = v1.T # Transposing v1
dot_product1 = np.dot(array_2d,v1t)
dot_product1

array([-617.8  , -641.1  , -594.2  , -595.6  , -602.8  , -754.2  ,
       -746.8  , -740.9  , -758.5  , -660.   , -612.6  , -627.8  ,
       -662.2  , -490.7  , -402.9  , -497.1  , -488.3  , -453.9  ,
       -355.   , -318.   , -465.9  , -417.   , -402.5  , -364.3  ,
       -463.6  , -805.5  , -765.2  , -760.4  , -840.9  , -355.   ,
       -379.8  , -373.1  , -331.965, -457.8  , -619.3  , -598.8  ,
       -597.4  , -589.6  , -745.3  , -791.3  , -740.3  , -730.2  ,
       -889.   , -851.2  , -927.5  , -519.4  , -423.6  , -587.4  ,
       -565.8  , -378.   , -351.6  , -349.8  , -345.   , -291.1  ,
       -253.1  , -309.8  , -330.   , -384.1  , -360.2  , -400.8  ,
       -416.6  , -381.2  , -759.3  , -775.5  , -737.   , -735.3  ,
       -642.4  , -811.6  , -809.9  , -799.2  , -776.4  , -398.5  ,
       -688.4  , -741.6  , -775.8  , -726.4  , -512.6  , -442.2  ,
       -531.3  , -377.3  , -414.   , -383.6  , -429.7  , -364.8  ,
       -349.   , -719.5  , -645.4  , -712.1  , -725.9  , -665.

### 8. Sorting
- Use NumPy to sort the cars by model_year in descending order and display the first
five car names.

In [153]:
array = np.array(df[["model year","car name"]]) # Creating array from data frame of model year and car name
sorted_array = np.sort(array, axis = 0)[ : : -1][:,1][ :5] # sorted the array along the columns using (axis = 0)
                                                           # reversed the sort to descending using [ : : -1]
                                                           # Extracted the second column elements (car name) from sorted array using [:,1]
                                                           # limited the result to 1st 5 car names using [ :5]
sorted_array.tolist()

['vw rabbit custom',
 'vw rabbit c (diesel)',
 'vw rabbit',
 'vw rabbit',
 'vw pickup']

### 9. Correlation
- Compute the Pearson correlation coefficient between mpg and weight using
NumPy.

In [154]:
x = np.array(df["mpg"])
y = np.array(df["weight"])
correlation_matrix = np.corrcoef(x,y)
pearson_correcoeff = correlation_matrix[0,1] # Extracting pearson corelation coefficient from the symmetric matrix
print("pearson_correlation_coefficient:",pearson_correcoeff)

pearson_correlation_coefficient: -0.8317409332443351


### 10.Conditional Aggregates
- Calculate the mean mpg for cars grouped by the number of cylinders using NumPy
techniques.

In [155]:
mpg_new = np.array(df["mpg"])
cylinders_new = np.array(df["cylinders"])
unique_cylinders = np.unique(cylinders_new) # Finding unique cylinder groups
unique_cylinders

array([3, 4, 5, 6, 8], dtype=int64)

In [156]:
mean_by_cyl = {} # Intializing dictionary
for cyl in unique_cylinders:
    mean_by_cyl[cyl] = np.round(np.mean(mpg_new[cylinders_new == cyl]),3) # Loop for finding mean of mpg for each group of cylinders
print(" Mean mpg by cylinder group:", mean_by_cyl)
    

 Mean mpg by cylinder group: {3: 20.55, 4: 29.287, 5: 27.367, 6: 19.986, 8: 14.963}


# Pandas

### 1. Basic Exploration
- Load the dataset into a Pandas DataFrame. Display:
   - The first 10 rows
   - The total number of rows and columns
   - Summary statistics for numerical columns

In [157]:
import pandas as pd
df = pd.read_csv("C:\\Users\\kiran\\Downloads\\auto-mpg.csv") # Data set loaded
df.head(10) # First 10 rows

mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   
3  16.0          8         304.0        150    3433          12.0          70   
4  17.0          8         302.0        140    3449          10.5          70   
5  15.0          8         429.0        198    4341          10.0          70   
6  14.0          8         454.0        220    4354           9.0          70   
7  14.0          8         440.0        215    4312           8.5          70   
8  14.0          8         455.0        225    4425          10.0          70   
9  15.0          8         390.0        190    3850           8.5          70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino  
5       1           ford galaxie 500  
6       1           chevrolet impala  
7       1          plymouth fury iii  
8       1           pontiac catalina  
9       1         amc ambassador dpl

In [158]:
df.shape # Rows and columns

(398, 9)

In [159]:
df.describe() # Summary statistics

mpg   cylinders  displacement       weight  acceleration  \
count  398.000000  398.000000    398.000000   398.000000    398.000000   
mean    23.514573    5.454774    193.425879  2970.424623     15.568090   
std      7.815984    1.701004    104.269838   846.841774      2.757689   
min      9.000000    3.000000     68.000000  1613.000000      8.000000   
25%     17.500000    4.000000    104.250000  2223.750000     13.825000   
50%     23.000000    4.000000    148.500000  2803.500000     15.500000   
75%     29.000000    8.000000    262.000000  3608.000000     17.175000   
max     46.600000    8.000000    455.000000  5140.000000     24.800000   

       model year      origin  
count  398.000000  398.000000  
mean    76.010050    1.572864  
std      3.697627    0.802055  
min     70.000000    1.000000  
25%     73.000000    1.000000  
50%     76.000000    1.000000  
75%     79.000000    2.000000  
max     82.000000    3.000000

### 2. Filtering and Indexing
- Find all cars manufactured in 1975 with a weight less than 3000. Return the
DataFrame with selected columns: car_name, weight, and mpg.

In [160]:
import numpy as np
df1 = np.array(df[df['model year']==75]['weight'])

In [161]:
df_new = df.loc[(df["model year"] == 75) & (df["weight"] <3000)]
df_new[['car name','weight','mpg']]

car name  weight   mpg
167     toyota corolla    2171  29.0
168         ford pinto    2639  23.0
169        amc gremlin    2914  20.0
170      pontiac astro    2592  23.0
171      toyota corona    2702  24.0
172  volkswagen dasher    2223  25.0
173         datsun 710    2545  24.0
174         ford pinto    2984  18.0
175  volkswagen rabbit    1937  29.0
177         audi 100ls    2694  23.0
178        peugeot 504    2957  23.0
179        volvo 244dl    2945  22.0
180          saab 99le    2671  25.0
181   honda civic cvcc    1795  33.0

### 3. Handling Missing Data
- Identify if there are any missing values in the dataset. Replace missing values in the
horsepower column with the column's median.

In [162]:
df.isna().sum() # Checking for null values

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [163]:
horsepower1 = df[df["horsepower"]!= "?"]["horsepower"] # Getting all the values other than "?"
horsepower1 =horsepower1.astype(float) # Converting values into type float
median = horsepower1.median() 
median # Median of remaining value

93.5

In [173]:
df['horsepower'] = df['horsepower'].replace('?', median) # Replace "?" with median value
df["horsepower_new"]=df['horsepower'].astype(float)
df["horsepower_new"]

0      130.0
1      165.0
2      150.0
3      150.0
4      140.0
       ...  
393     86.0
394     52.0
395     84.0
396     79.0
397     82.0
Name: horsepower_new, Length: 398, dtype: float64

### 4. Data Transformation
- Add a new column power_to_weight_ratio, calculated as horsepower / weigh

In [174]:
df["power_to weight_ratio"]  = df["horsepower"].astype(float) / df["weight"]
df

mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130    3504          12.0   
1    15.0          8         350.0        165    3693          11.5   
2    18.0          8         318.0        150    3436          11.0   
3    16.0          8         304.0        150    3433          12.0   
4    17.0          8         302.0        140    3449          10.5   
..    ...        ...           ...        ...     ...           ...   
393  27.0          4         140.0         86    2790          15.6   
394  44.0          4          97.0         52    2130          24.6   
395  32.0          4         135.0         84    2295          11.6   
396  28.0          4         120.0         79    2625          18.6   
397  31.0          4         119.0         82    2720          19.4   

     model year  origin                   car name  power_to weight_ratio  \
0            70       1  chevrolet chevelle malibu               0.037100   
1            70       1          buick skylark 320               0.044679   
2            70       1         plymouth satellite               0.043655   
3            70       1              amc rebel sst               0.043694   
4            70       1                ford torino               0.040591   
..          ...     ...                        ...                    ...   
393          82       1            ford mustang gl               0.030824   
394          82       2                  vw pickup               0.024413   
395          82       1              dodge rampage               0.036601   
396          82       1                ford ranger               0.030095   
397          82       1                 chevy s-10               0.030147   

     performance_score  horsepower_new  
0             0.061644           130.0  
1             0.046710           165.0  
2             0.057625           150.0  
3             0.055928           150.0  
4             0.051754           140.0  
..                 ...             ...  
393           0.150968            86.0  
394           0.508169            52.0  
395           0.161743            84.0  
396           0.198400            79.0  
397           0.221103            82.0  

[398 rows x 12 columns]

### 5. Group By
- Group the cars by origin and calculate the mean mpg for each group.

In [166]:
# Group by orgin
groupby_origin = df.groupby("origin")

In [167]:
#Calculating mean for each group
grouped_mean = df.groupby("origin").mean("mpg")
grouped_mean["mpg"]

origin
1    20.083534
2    27.891429
3    30.450633
Name: mpg, dtype: float64

### 6. Sorting
- Sort the DataFrame by mpg in descending order and display the top 10 cars with
the highest mpg.


In [168]:
df_new1 = df.sort_values(by = "mpg",ascending = False)
df_new1["car name"].head(10)


322                          mazda glc
329                honda civic 1500 gl
325               vw rabbit c (diesel)
394                          vw pickup
326                 vw dasher (diesel)
244    volkswagen rabbit custom diesel
309                          vw rabbit
330               renault lecar deluxe
324                         datsun 210
247                     datsun b210 gx
Name: car name, dtype: object

### 7. Apply Function
- Create a new column performance_score using a custom function:
   - def performance_score(row):
   - return row['mpg']* row['acceleration'] / row['weight']
- Apply this function to each row and store the result in the new column

In [169]:
def performance_score(row):
    new_column = row['mpg']* row['acceleration'] / row['weight']
    return new_column
df["performance_score"]  = df.apply(performance_score, axis =1) # axis = 1 performs the df.apply() function in row wise manner.
df

mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130    3504          12.0   
1    15.0          8         350.0        165    3693          11.5   
2    18.0          8         318.0        150    3436          11.0   
3    16.0          8         304.0        150    3433          12.0   
4    17.0          8         302.0        140    3449          10.5   
..    ...        ...           ...        ...     ...           ...   
393  27.0          4         140.0         86    2790          15.6   
394  44.0          4          97.0         52    2130          24.6   
395  32.0          4         135.0         84    2295          11.6   
396  28.0          4         120.0         79    2625          18.6   
397  31.0          4         119.0         82    2720          19.4   

     model year  origin                   car name  power_to weight_ratio  \
0            70       1  chevrolet chevelle malibu               0.037100   
1            70       1          buick skylark 320               0.044679   
2            70       1         plymouth satellite               0.043655   
3            70       1              amc rebel sst               0.043694   
4            70       1                ford torino               0.040591   
..          ...     ...                        ...                    ...   
393          82       1            ford mustang gl               0.030824   
394          82       2                  vw pickup               0.024413   
395          82       1              dodge rampage               0.036601   
396          82       1                ford ranger               0.030095   
397          82       1                 chevy s-10               0.030147   

     performance_score  
0             0.061644  
1             0.046710  
2             0.057625  
3             0.055928  
4             0.051754  
..                 ...  
393           0.150968  
394           0.508169  
395           0.161743  
396           0.198400  
397           0.221103  

[398 rows x 11 columns]

### 8. Visualization Preparation
Generate a summary DataFrame with:
- Average mpg, weight, and horsepower for each model_year

In [175]:

grouped_mean = df.groupby("origin")[["mpg","weight","horsepower_new"]].mean()
print(grouped_mean)


              mpg       weight  horsepower_new
origin                                        
1       20.083534  3361.931727      118.638554
2       27.891429  2423.300000       80.928571
3       30.450633  2221.227848       79.835443


### 9. Exporting Data
- Save a subset of the data containing only mpg, cylinders, horsepower, and weight
for cars with mpg > 30 into a CSV file named high_mpg_cars.csv.

In [176]:
new_df4 = df[df["mpg"]>30]
high_mpg_cars = new_df4[["mpg","cylinders","horsepower","weight"]]
high_mpg_cars

mpg  cylinders horsepower  weight
53   31.0          4         65    1773
54   35.0          4         69    1613
129  31.0          4         67    1950
131  32.0          4         65    1836
144  31.0          4         52    1649
..    ...        ...        ...     ...
390  32.0          4         96    2665
391  36.0          4         84    2370
394  44.0          4         52    2130
395  32.0          4         84    2295
397  31.0          4         82    2720

[85 rows x 4 columns]

In [117]:
import os
file = open(os.path.join("C:\\Users","kiran","OneDrive","Documents","Case study","high_mpg_cars.csv"),"x") # Creating file

In [120]:
high_mpg_cars.to_csv(os.path.join("C:\\Users","kiran","OneDrive","Documents","Case study","high_mpg_cars.csv")) # Writing data to csv file

In [177]:
high_mpg_cars_df = pd.read_csv(os.path.join("C:\\Users","kiran","OneDrive","Documents","Case study","high_mpg_cars.csv"))
high_mpg_cars_df

Unnamed: 0   mpg  cylinders  horsepower  weight
0           53  31.0          4        65.0    1773
1           54  35.0          4        69.0    1613
2          129  31.0          4        67.0    1950
3          131  32.0          4        65.0    1836
4          144  31.0          4        52.0    1649
..         ...   ...        ...         ...     ...
80         390  32.0          4        96.0    2665
81         391  36.0          4        84.0    2370
82         394  44.0          4        52.0    2130
83         395  32.0          4        84.0    2295
84         397  31.0          4        82.0    2720

[85 rows x 5 columns]

### 10. Finding Anomalies
- Identify potential outliers in the mpg column using the Interquartile Range (IQR)
method. Specifically:
  - Calculate the IQR for mpg.
  - Define outliers as values less than Q1 - 1.5 * IQR or greater than Q3 +
1.5 * IQR.
  - Create a DataFrame of cars classified as outliers, displaying car_name, mpg,
and model_year

In [181]:
# Calculate the IQR for mpg.
Q1 = df['mpg'].quantile(0.25)
Q3 = df['mpg'].quantile(0.75)
IQR = Q3 - Q1
IQR

11.5

In [182]:
# Define outliers as values less than Q1 - 1.5 * IQR or greater than Q3 + 1.5 * IQR.
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers = df[(df['mpg'] < lower_bound) | (df['mpg'] > upper_bound)]
outliers

mpg  cylinders  displacement horsepower  weight  acceleration  \
322  46.6          4          86.0         65    2110          17.9   

     model year  origin   car name  power_to weight_ratio  performance_score  \
322          80       3  mazda glc               0.030806           0.395327   

     horsepower_new  
322            65.0

In [185]:
# Create a DataFrame of cars classified as outliers, displaying car_name, mpg, and model_year
outliers_df = outliers[['car name', 'mpg', 'model year']]
outliers_df

car name   mpg  model year
322  mazda glc  46.6          80